version: "3.8"

services:
  db:
    image: postgres:14
    ports:
      - "6432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
  server:
    build: /server
    depends_on:
      - db
    ports:
      - "3000:8080"
    restart: always
    environment:
      ENV: dev
      DB_USER: postgres
      DB_PASS: secret
      DB_HOST: db
      DB_NAME: postgres
      DB_TEST_NAME: school_test
      DB_PORT: 5432
      BCRYPT_SECRET: BcryptSecret
      BCRYPT_SALT: 10
      JWT_SECRET: JwtSecret
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 587
      MAIL_USER: 08ecd36cc247cb
      MAIL_PASS: 40543242697c2b
    volumes:
      - server-data:/storage 
  web:
    build: /website
    ports:
      - "8080:8080"

volumes:
  db-data:
  server-data:
